"""init

Revision ID: 51db75cc5a59
Revises: eb79ee7d9c19
Create Date: 2025-08-21 08:47:22.462003

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "51db75cc5a59"
down_revision: Union[str, Sequence[str], None] = "eb79ee7d9c19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
