"""Update assets and remove ticker column

Revision ID: 5d3cee37c67b
Revises: 790450bdfb07
Create Date: 2025-09-04 18:29:46.103508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3cee37c67b'
down_revision: Union[str, Sequence[str], None] = '790450bdfb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'ticker')
    op.add_column('assets', sa.Column('exchange', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'exchange')
    op.add_column('allocations', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
