"""Adding ticker and buy date in allocation

Revision ID: 8a9b44788ded
Revises: 51db75cc5a59
Create Date: 2025-09-02 08:58:39.739587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9b44788ded'
down_revision: Union[str, Sequence[str], None] = '51db75cc5a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('allocations', sa.Column('buy_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'buy_date')
    op.drop_column('allocations', 'ticker')
    # ### end Alembic commands ###
