"""Adding Price Quots

Revision ID: f339b296c6da
Revises: 8a9b44788ded
Create Date: 2025-09-03 20:59:07.917519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f339b296c6da'
down_revision: Union[str, Sequence[str], None] = '8a9b44788ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_quotes',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_price_quotes_updated_at'), 'price_quotes', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_quotes_updated_at'), table_name='price_quotes')
    op.drop_table('price_quotes')
    # ### end Alembic commands ###
